### ISSUE TITLE
Switch to alert causing test to fail even when exception is catched

### ISSUE THREAD

**Issue by Rantzur1992** [testproject-io/java-opensdk#71]
Code:
```
 @Test
    public void tester() throws InvalidTokenException, AgentConnectException, ObsoleteVersionException, IOException {
        ChromeDriver driver = new ChromeDriver(new ChromeOptions());
        Reporter report = driver.report();

        driver.navigate().to("https://example.testproject.io/web/");
        try {
            driver.switchTo().alert();
        } catch (Exception ignored) {
        }
        driver.findElement(By.cssSelector("#name")).sendKeys("John Smith");
        driver.findElement(By.cssSelector("#password")).sendKeys("12345");
        new Actions(driver).click(driver.findElement(By.cssSelector("#login"))).build().perform();

        boolean passed = driver.findElement(By.cssSelector("#logout")).isDisplayed();
        if (passed) {
            System.out.println("Test Passed");
        } else {
            System.out.println("Test Failed");
        }

        driver.quit();
    }
```

When switching to the alert, and the alert is not present, an exception is thrown, and I catch it and the test passes in the IDE.
But in the report, you can see the step is generated and fails the test.
It also shows in the report the step tries to take the text of the alert which is not correct.
![image](https://user-images.githubusercontent.com/6703682/104588761-8950d000-5671-11eb-84d7-966d35f3b5b8.png)

![image](https://user-images.githubusercontent.com/6703682/104588783-92da3800-5671-11eb-879e-5e723843c0f8.png)

**Comment by DavidG8168** [comment]
@Rantzur1992 As for this issue, 

1. Driver commands are reported regardless if their exceptions are caught, this is by design, if you would like to control this behavior you will need to disable automatic command reporting and then re-enable it once you're done.

2. Behind the scenes the driver command being executed by `driver.switchTo().alert();` is the 'GET_ALERT_TEXT' command, so that's what you're seeing in the report, because that's what failed. If you were to do `driver.switchTo().alert().accept` you'll see both the get text and accept alert commands reported.

**Comment by Rantzur1992** [comment]
Why report as failed tho?
@mstrelex IMO if the exception is caught, the intention is to pass the step.
I did tell him to disable and enable but it is redundant for multiple steps..

**Comment by DavidG8168** [comment]
See previous comment.
https://github.com/testproject-io/java-opensdk/issues/71#issuecomment-760300806
